### ISSUE TITLE
libtd build failed while installing from aur package

### ISSUE THREAD

**Issue by therajat08** [paul-nameless/tg#198]
i tried installing tg with `yay -S telegram-tg`

It lead to compilation of libtd, think. It was taking 100% cpu usage and near 75% completion took all of my ram (8 gb). and then failed. 

later i tried pip3 which was quick and successfull. 

I just wanted to know what happened with aur package method. and do i need to be worried about changes it might have caused to my system.

took this screenshot of what was going in between
[screenshot](https://imgur.com/206q3Dm)

**Comment by jugendhacker** [comment]
Hi, I'm the maintainer of the AUR package.
If you use the AUR package your PC needs to build libtd because `python-telegram` (which tg is based on) depends on libtd. The pip way is fast and without a build of libtd, but it then uses precompile binaries provided by the `python-telegram` devs (see https://github.com/alexander-akhmetov/python-telegram/tree/master/telegram/lib and alexander-akhmetov/python-telegram#119), which in my opinion is not acceptable for a non `-bin` package and so I patched `python-telegram` to use the system wide install of libtd.

**Comment by therajat08** [comment]
yeah. But in my case build failed in between maybe  with some overflow error. i just hope that failed build didn't mess up other things that were dependent on it. I am a noob so just very cautious.

**Comment by jugendhacker** [comment]
If you had to build libtd than most likely none of your already installed packages depends on it and so it's unlikely you broke something when libtd failed to build.

**Comment by therajat08** [comment]
cool
