### ISSUE TITLE
[Feature Request] Per user colors

### ISSUE THREAD

**Issue by y4my4my4m** [paul-nameless/tg#92]
In group chats, it's making it quite hard to distinguish who's who.

Even in 1on1 chats, it can get confusing.

Any way we can have random colors (or even predefined) colors on a user basis?

**Comment by paul-nameless** [comment]
We definitely should implement this feature.
To give best user experience we should keep user colors persistent between restart to avoid confusion.
Also, currently our color scheme limited to 16bit colors to make color schemes in terminal consistent. So that should be taken in account and either implemented within 16bit color range or with optional rgb colors but making sure colors still look consistent on different terminals and color schemes.

**Comment by y4my4my4m** [comment]
@paul-nameless 
I'd recommend starting with 16color range and eventually update to optional rgb :)

**Comment by paul-nameless** [comment]
Released 0.2.0 version with this feature included

**Comment by y4my4my4m** [comment]
@paul-nameless It's glorious! Thank you so much :)
