### ISSUE TITLE
View glitch

### ISSUE THREAD

**Issue by jugendhacker** [paul-nameless/tg#96]
If I open message view and then press `a` to write a message this glitch appears:
![image](https://user-images.githubusercontent.com/12773748/86105768-06df3500-bac0-11ea-9d84-e260263b7eb1.png)

Is it known?

**Comment by lightme16** [comment]
Me also having similar problems with this border. However, for me,  I believe the root cause it usage of the emojis for chat labels. 
<img width="57" alt="image" src="https://user-images.githubusercontent.com/9078927/86110860-bcb18000-bace-11ea-9b39-470f7fc62825.png">
We will improve this code to make it more robust for different configurations. 

For your case, do you have any emojis in the chat name? Or in the message in the same row?

**Comment by jugendhacker** [comment]
Yes Emojis seem to be the problem... maybe their width is calculated wrong?

**Comment by paul-nameless** [comment]
Yes, this is a bug with calculating correctly utf-8 dobule width symbols.
We are trying to count them, but apparently it's not working perfectly.
Need to have a look closely.
